version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      # You can give any username
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mypassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      # Default database
      MYSQL_DATABASE: 'shop'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - /shop/mysql_data:/var/lib/mysql
      - /media/sf_LinuxSharedFolder/shop-management/init:/docker-entrypoint-initdb.d/:ro
    hostname: mysql
  users:
    image: node_server
    container_name: node
    environment:
      - MYSQL_HOST=mysql
      - USERNAME=root
      - PASSWORD=rootpassword
      - DATABASE_NAME=shop
    ports:
      - '5001:5001'
    volumes:
      - '/media/sf_LinuxSharedFolder/shop-management:/usr/src/app'
    links:
      - mysql
    hostname: users
  swagger:
    image: swaggerapi/swagger-editor
    container_name: swagger
    ports:
      - '8080:8080'


